"""Schema update

Revision ID: 1a15eb10b20a
Revises: 33be68251af9
Create Date: 2026-02-09 16:53:13.829957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a15eb10b20a'
down_revision = '33be68251af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_manual', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('exchange_rate_target_currency_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('exchange_rate_base_currency_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('exchange_rate_base_currency_fkey'), 'currency', ['base_currency'], ['code'])
        batch_op.create_foreign_key(batch_op.f('exchange_rate_target_currency_fkey'), 'currency', ['target_currency'], ['code'])
        batch_op.drop_column('is_manual')

    # ### end Alembic commands ###
